name: Build Debug

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  run:
    continue-on-error: false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-jave@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/cache@v3
        with:
          path:
            ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-

      - name: Build App
        run: ./gradlew :app:assembleDebug --no-build-cache

      - uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
